version: '3'
services:
    database:
        container_name: phpmyadmin_cocclock
        image: phpmyadmin/phpmyadmin
        ports:
            - "8085:80"
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - mariadb
    mariadb:
        container_name: mariadb_cocclock
        image: mariadb:latest
        ports:
            - "3310:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mariadb:/var/lib/mysql
