version: '3'

networks:
    cocclock-net:
        driver: bridge

services:
    mariadb:
        container_name: mariadb_cocclock
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: nd8XFtVP82gfQgeNFrrvdArF54Sd2bK4
            MYSQL_DATABASE: cocclock
        volumes:
            - ./mariadb:/var/lib/mysql
        networks:
            - cocclock-net

    database:
        container_name: phpmyadmin_cocclock
        image: phpmyadmin/phpmyadmin
        ports:
            - "9011:80"
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - mariadb
        networks:
            - cocclock-net

    app:
        container_name: cocclock_app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5050:5000"
        volumes:
            - .:/app
        depends_on:
            - mariadb
        networks:
            - cocclock-net
