version: '3'
services:
    database:
        container_name: phpmyadmin_cocclock
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - mariadb
    mariadb:
        container_name: mariadb
        image: mariadb:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cocclock
        volumes:
            - ./mariadb:/var/lib/mysql
