[tool.poetry]
name = "clash of clan clock"
version = "0.1.0"
description = ""
authors = ["as6325400 <as6325400@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
